gog: treat "init" funcs in same Go package as separate (since multiple separate init funcs can exist at top level)
Fixes test failure (which was not being triggered by Travis CI, since
Travis CI until the previous commit was not running Go unit tests):

--- FAIL: TestPaths (0.00s)
	path_test.go:69: "func init() { x:=0;_=x};func init() { x:=0;_=x}": path not found: {pkg:foo path:init$sources[0]28/x}
	path_test.go:69: "func init() { x:=0;_=x};func init() { x:=0;_=x}": path not found: {pkg:foo path:init$sources[0]52/x}
	path_test.go:84:
		### Code:
		package foo; /*START*/ func init() { x:=0;_=x};func init() { x:=0;_=x} /*END*/
		### All paths:
	path_test.go:86:   {pkg:foo path:init$sources[0]52}
	path_test.go:86:   {pkg:foo path:init/x}
	path_test.go:86:   {pkg:foo path:init$1/x}
	path_test.go:86:   {pkg:foo path:init$sources[0]28}
FAIL
FAIL	sourcegraph.com/sourcegraph/srclib-go/gog	0.009s

Also fixes the issue where a Go package with multiple init funcs that
declared local vars of the same name would fail the srclib graph data
normalization step with the following error (e.g.):

skipping unit sourcegraph.com/sourcegraph/sourcegraph/server/internal/localstore because failed to normalize data: duplicate def key: {Repo: CommitID: UnitType:GoPackage Unit:sourcegraph.com/sourcegraph/sourcegraph/server/internal/localstore Path:init/err}